import re
import json
import argparse
import requests
import sys
from urllib.parse import urlparse, parse_qs
from datetime import datetime

# -------------------------------------------------------------------------
# Tool: Revelator
# Author: R00t3dbyFa17h
# Verse: "He reveals deep and hidden things..." (Daniel 2:22)
# Description: Advanced JS Analysis, API Reconstruction, and Secret Hunting.
# -------------------------------------------------------------------------

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def banner():
    print(Colors.HEADER + r"""
    ____  _______    ____________    ___  __________  ____ 
   / __ \/ ____/ |  / / ____/ /   /   |/_  __/ __ \/ __ \
  / /_/ / __/  | | / / __/ / /   / /| | / / / / / / /_/ /
 / _, _/ /___  | |/ / /___/ /___/ ___ |/ / / /_/ / _, _/ 
/_/ |_/_____/  |___/_____/_____/_/  |_/_/  \____/_/ |_|  
                                            v1.0
    """ + Colors.ENDC)
    print(Colors.BOLD + " [*] Revealing the deep and hidden things (Daniel 2:22)..." + Colors.ENDC)

def fetch_js(url):
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Revelator-Scanner)'}
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            return response.text
    except Exception as e:
        print(Colors.FAIL + f" [!] Error fetching URL: {e}" + Colors.ENDC)
        return None

def scan_secrets(content):
    signatures = {
        "AWS Access Key": r"AKIA[0-9A-Z]{16}",
        "Google API Key": r"AIza[0-9A-Za-z\\-_]{35}",
        "Generic API Key": r"(api_key|access_token|secret_key)\s*[:=]\s*['\"]([a-zA-Z0-9_\-]{10,})['\"]",
        "Authorization Bearer": r"Bearer\s[a-zA-Z0-9\-\._~+\/]+=*"
    }
    found_secrets = []
    for name, pattern in signatures.items():
        matches = re.findall(pattern, content)
        for match in matches:
            secret_val = match if isinstance(match, str) else match[1]
            found_secrets.append({"type": name, "value": secret_val})
    return found_secrets

def extract_endpoints(js_content):
    pattern = r"(get|post|put|delete|patch)\(['\"]([^'\"]+)['\"]"
    matches = re.findall(pattern, js_content, re.IGNORECASE)
    return matches

def generate_html_report(swagger, secrets, filename="revelator_report.html"):
    html = f"""
    <html>
    <head>
        <title>Revelator Scan Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0f0f0f; color: #e0e0e0; padding: 40px; }}
            h1 {{ color: #9b59b6; border-bottom: 2px solid #9b59b6; padding-bottom: 10px; }}
            h2 {{ color: #3498db; margin-top: 30px; }}
            .card {{ background: #1e1e1e; padding: 15px; margin: 10px 0; border-radius: 5px; border-left: 5px solid #2ecc71; }}
            .secret {{ border-left: 5px solid #e74c3c; background: #2c0e0e; }}
            .method {{ font-weight: bold; color: #fff; background: #3498db; padding: 3px 8px; border-radius: 3px; font-size: 0.9em; }}
            .footer {{ margin-top: 50px; font-size: 0.8em; color: #777; }}
        </style>
    </head>
    <body>
        <h1>REVELATOR // Scan Report</h1>
        <p><b>Target:</b> API Infrastructure Analysis</p>
        <p><b>Date:</b> {datetime.now()}</p>
        
        <h2>[+] Secrets Detected ({len(secrets)})</h2>
        {'<p>No hardcoded secrets found.</p>' if not secrets else ''}
        {''.join([f'<div class="card secret"><b>{s["type"]}:</b> {s["value"]}</div>' for s in secrets])}

        <h2>[+] API Map ({len(swagger['paths'])})</h2>
        {''.join([f'<div class="card"><span class="method">{m.upper()}</span> {p}</div>' for p, m_dict in swagger['paths'].items() for m in m_dict])}
        
        <div class="footer">Generated by Revelator | R00t3dbyFa17h</div>
    </body>
    </html>
    """
    with open(filename, "w") as f:
        f.write(html)
    print(Colors.GREEN + f" [+] HTML Report generated: {filename}" + Colors.ENDC)

def main():
    parser = argparse.ArgumentParser(description="Revelator: The JS Reconnaissance Framework")
    req_group = parser.add_argument_group('Target Options')
    req_group.add_argument("-u", "--url", help="Target JS File URL", required=True)
    req_group.add_argument("-t", "--target", help="Base API URL (e.g., https://api.target.com)", required=True)
    
    opt_group = parser.add_argument_group('Output Options')
    opt_group.add_argument("-o", "--output", help="JSON Output Filename", default="swagger.json")
    opt_group.add_argument("--html", help="Generate HTML Report", action="store_true")
    
    args = parser.parse_args()
    banner()

    print(Colors.BLUE + f" [+] Fetching JS from {args.url}..." + Colors.ENDC)
    js_content = fetch_js(args.url)
    
    if js_content:
        print(Colors.BLUE + " [+] Analyzing for API logic..." + Colors.ENDC)
        matches = extract_endpoints(js_content)
        
        swagger_data = {
            "openapi": "3.0.0", 
            "info": {"title": "Revelator Scan", "version": "1.0"},
            "paths": {}
        }
        
        for method, raw_path in matches:
            parsed = urlparse(raw_path)
            clean_path = parsed.path
            if clean_path not in swagger_data["paths"]:
                swagger_data["paths"][clean_path] = {}
            swagger_data["paths"][clean_path][method.lower()] = {"responses": {"200": {"desc": "OK"}}}

        print(Colors.GREEN + f" [+] Identified {len(matches)} endpoints." + Colors.ENDC)

        print(Colors.WARNING + " [+] Hunting for hidden secrets..." + Colors.ENDC)
        secrets = scan_secrets(js_content)
        if secrets:
            print(Colors.FAIL + f" [!!!] FOUND {len(secrets)} POTENTIAL SECRETS!" + Colors.ENDC)
            for s in secrets:
                print(f"     - {s['type']}: {s['value'][:15]}...")
        else:
            print("     - No obvious secrets found.")

        with open(args.output, "w") as f:
            json.dump(swagger_data, f, indent=4)
        print(Colors.GREEN + f" [+] Swagger JSON saved to: {args.output}" + Colors.ENDC)
        
        if args.html:
            generate_html_report(swagger_data, secrets)

if __name__ == "__main__":
    main()